# Maximum range sensor reading in meters that results in an obstacle being placed in the costmap
obstacle_range: 10.0

# Outside of this range is considered free space
raytrace_range: 15.0

# Footprint of the robot with (0,0) being the center (in meters)
footprint: [[-0.7, -0.5], [-0.7, 0.5], [0.7, 0.5], [0.7, -0.5]]

# The static map created using SLAM is being published to this topic
map_topic: /map

# Global reference frame for the costmaps
global_frame: map

# Base frame of the robot
robot_base_frame: base_link

# Frequency in Hz for the costmap to be updated
update_frequency: 5.0

# Frequency in Hz for the costmap to publish display information
publish_frequency: 5.0

# Delay in transform tf data that is tolerable in seconds
transform_tolerance: 0.2

# Width of the map in meters
width: 75

# Height of the map in meters
height: 75

publish_voxel_map: true
map_type: costmap

rolling_window: true

subscribe_to_updates: true

# Each costmap is layered
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: /map
  subscribe_to_updates: true


obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_link, 
                        data_type: LaserScan, 
                        topic: scan, marking: true, 
                        clearing: true, 
                        max_obstacle_height: 3, 
                        min_obstacle_height: -3, 
                        inf_is_valid: true, 
                        obstacle_range: 10, 
                        combination_method: 0,
                        raytrace_range: 15}

inflation_layer:
  inflation_radius: 1.0
  cost_scaling_factor: 0.5



