local_costmap: 
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 5.0 # may be changed if error shows
  publish_frequency: 5.0 # may be changed if error shows. 
  transform_tolerance: 0.2 

  static_map: false
  rolling_window: true
  width: 15 
  height: 15
  resolution: 0.05 

